### ISSUE TITLE
Crash at install

### ISSUE THREAD

**Issue by exciton** [corbindavenport/creative-cloud-linux#11]
Adobe Installer is crashing at 3% download point...

Any clues?

Unhandled exception: page fault on read access to 0x00000050 in 32-bit code (0x7d76fc0a).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7d76fc0a ESP:0076e5f0 EBP:0076e648 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:00180fc0 EBX:7d7def08 ECX:00180ce8 EDX:00000000
 ESI:00180cd0 EDI:0076e680
Stack dump:
0x0076e5f0:  00180fc0 00180ce8 00000000 7bd0d5c4
0x0076e600:  00000000 7d80dbe0 7d800010 7bc7498e
0x0076e610:  001b56e0 00000020 00169c98 00000001
0x0076e620:  00169c68 00000020 0076e648 00000000
0x0076e630:  00000040 00000002 0076e698 7d7def08
0x0076e640:  00180ce8 0076e790 0076e6b8 7d74f4dd
Backtrace:
=>0 0x7d76fc0a in msxml3 (+0x5fc0a) (0x0076e648)
  1 0x7d74f4dd in msxml3 (+0x3f4dc) (0x0076e6b8)
  2 0x7d7705b9 in msxml3 (+0x605b8) (0x0076e738)
  3 0x7d748d4e in msxml3 (+0x38d4d) (0x0076e770)
  4 0x004c89d3 in creativecloudset-up (+0xc89d2) (0x0076e798)
  5 0x004cb9f4 in creativecloudset-up (+0xcb9f3) (0x0076e7d4)
  6 0x00429220 in creativecloudset-up (+0x2921f) (0x0076e8a0)
  7 0x00427111 in creativecloudset-up (+0x27110) (0x0076e9d4)
  8 0x00426b3e in creativecloudset-up (+0x26b3d) (0x0076e9e8)
  9 0x7bcad834 call_thread_func_wrapper+0xb() in ntdll (0x0076ea08)
  10 0x7bcb0fdd in ntdll (+0x70fdc) (0x0076eae8)
  11 0x7bcad812 RtlRaiseException+0x49() in ntdll (0x0076eb08)
  12 0x7bcb8ebc in ntdll (+0x78ebb) (0x0076f358)
  13 0xf7548f72 start_thread+0xd1() in libpthread.so.0 (0x0076f428)
  14 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  15 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  16 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  17 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  18 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  19 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  20 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  21 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  22 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  23 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  24 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  25 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  26 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  27 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  28 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  29 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  30 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  31 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  32 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  33 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  34 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  35 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  36 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  37 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  38 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  39 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  40 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  41 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  42 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  43 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  44 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  45 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  46 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  47 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  48 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  49 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  50 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  51 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  52 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  53 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  54 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  55 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  56 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  57 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  58 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  59 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  60 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  61 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  62 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  63 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  64 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  65 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  66 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  67 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  68 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  69 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  70 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  71 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  72 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  73 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  74 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  75 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  76 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  77 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  78 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  79 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  80 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  81 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  82 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  83 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  84 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  85 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  86 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  87 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  88 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  89 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  90 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  91 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  92 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  93 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  94 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  95 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  96 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  97 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  98 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  99 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  100 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  101 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  102 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  103 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  104 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  105 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  106 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  107 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  108 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  109 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  110 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  111 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  112 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  113 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  114 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  115 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  116 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  117 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  118 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  119 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  120 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  121 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  122 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  123 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  124 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  125 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  126 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  127 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  128 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  129 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  130 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  131 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  132 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  133 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  134 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  135 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  136 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  137 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  138 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  139 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  140 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  141 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  142 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  143 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  144 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  145 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  146 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  147 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  148 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  149 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  150 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  151 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  152 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  153 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  154 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  155 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  156 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  157 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  158 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  159 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  160 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  161 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  162 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  163 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  164 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  165 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  166 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  167 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  168 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  169 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  170 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  171 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  172 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  173 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  174 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  175 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  176 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  177 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  178 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  179 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  180 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  181 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  182 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  183 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  184 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  185 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  186 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  187 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  188 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  189 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  190 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  191 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  192 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  193 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  194 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  195 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  196 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  197 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  198 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  199 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
  200 0xf747f3ee __clone+0x5d() in libc.so.6 (0x00000000)
0x7d76fc0a: call	*0x50(%edx)
Modules:
Module	Address			Debug info	Name (139 modules)
PE	  400000-  66a000	Export          creativecloudset-up
ELF	7a800000-7a93a000	Deferred        opengl32<elf>
  \-PE	7a820000-7a93a000	\               opengl32
ELF	7b400000-7b7f6000	Deferred        kernel32<elf>
  \-PE	7b420000-7b7f6000	\               kernel32
ELF	7bc00000-7bd2b000	Dwarf           ntdll<elf>
  \-PE	7bc40000-7bd2b000	\               ntdll
ELF	7c000000-7c003000	Deferred        <wine-loader>
ELF	7cdcb000-7cde8000	Deferred        libgcc_s.so.1
ELF	7ce0d000-7ce27000	Deferred        cryptnet<elf>
  \-PE	7ce10000-7ce27000	\               cryptnet
ELF	7ce27000-7ce45000	Deferred        bcrypt<elf>
  \-PE	7ce30000-7ce45000	\               bcrypt
ELF	7ce45000-7ce85000	Deferred        rsaenh<elf>
  \-PE	7ce50000-7ce85000	\               rsaenh
ELF	7ce85000-7ceb5000	Deferred        netapi32<elf>
  \-PE	7ce90000-7ceb5000	\               netapi32
ELF	7ceb5000-7cee9000	Deferred        secur32<elf>
  \-PE	7cec0000-7cee9000	\               secur32
ELF	7cee9000-7cef0000	Deferred        libnss_dns.so.2
ELF	7cef0000-7cef7000	Deferred        libffi.so.6
ELF	7cef7000-7cefc000	Deferred        libgpg-error.so.0
ELF	7cefc000-7cf00000	Deferred        libkeyutils.so.1
ELF	7cf00000-7cf4b000	Deferred        libdbus-1.so.3
ELF	7cf4b000-7cf87000	Deferred        libp11-kit.so.0
ELF	7cf87000-7d00c000	Deferred        libgcrypt.so.11
ELF	7d00c000-7d01e000	Deferred        libtasn1.so.3
ELF	7d01e000-7d02a000	Deferred        libkrb5support.so.0
ELF	7d02a000-7d02f000	Deferred        libcom_err.so.2
ELF	7d02f000-7d05f000	Deferred        libk5crypto.so.3
ELF	7d05f000-7d11e000	Deferred        libkrb5.so.3
ELF	7d11e000-7d130000	Deferred        libavahi-client.so.3
ELF	7d130000-7d1f9000	Deferred        libgnutls.so.26
ELF	7d1f9000-7d23f000	Deferred        libgssapi_krb5.so.2
ELF	7d23f000-7d2ac000	Deferred        libcups.so.2
ELF	7d2ac000-7d408000	Deferred        wined3d<elf>
  \-PE	7d2c0000-7d408000	\               wined3d
ELF	7d408000-7d432000	Deferred        dxgi<elf>
  \-PE	7d410000-7d432000	\               dxgi
ELF	7d432000-7d475000	Deferred        winspool<elf>
  \-PE	7d440000-7d475000	\               winspool
ELF	7d475000-7d4af000	Deferred        wbemprox<elf>
  \-PE	7d480000-7d4af000	\               wbemprox
ELF	7d4af000-7d4ed000	Deferred        libxslt.so.1
ELF	7d4ed000-7d52c000	Deferred        ws2_32<elf>
  \-PE	7d4f0000-7d52c000	\               ws2_32
ELF	7d52c000-7d5a9000	Deferred        wininet<elf>
  \-PE	7d540000-7d5a9000	\               wininet
ELF	7d5a9000-7d705000	Deferred        libxml2.so.2
ELF	7d705000-7d800000	Dwarf           msxml3<elf>
  \-PE	7d710000-7d800000	\               msxml3
ELF	7d903000-7d92d000	Deferred        iphlpapi<elf>
  \-PE	7d910000-7d92d000	\               iphlpapi
ELF	7d92d000-7d9d2000	Deferred        urlmon<elf>
  \-PE	7d940000-7d9d2000	\               urlmon
ELF	7da2a000-7da42000	Deferred        libresolv.so.2
ELF	7da42000-7da6a000	Deferred        mpr<elf>
  \-PE	7da50000-7da6a000	\               mpr
ELF	7da6a000-7da90000	Deferred        liblzma.so.5
ELF	7daa0000-7dab5000	Deferred        schannel<elf>
  \-PE	7dab0000-7dab5000	\               schannel
ELF	7daed000-7db00000	Deferred        api-ms-win-core-sysinfo-l1-2-1<e
PE	7daf0000-7db00000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	7db46000-7db59000	Deferred        api-ms-win-core-localization-l1-
PE	7db50000-7db59000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	7db59000-7db6c000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	7db60000-7db6c000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	7db6c000-7dba4000	Deferred        uxtheme<elf>
  \-PE	7db70000-7dba4000	\               uxtheme
ELF	7dba4000-7dbaa000	Deferred        libxfixes.so.3
ELF	7dbaa000-7dbb5000	Deferred        libxcursor.so.1
ELF	7dbb7000-7dbc5000	Deferred        libavahi-common.so.3
ELF	7dbc5000-7dbd8000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	7dbd0000-7dbd8000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	7dc57000-7dc80000	Deferred        libexpat.so.1
ELF	7dc80000-7dcbb000	Deferred        libfontconfig.so.1
ELF	7dce0000-7dd7c000	Deferred        libfreetype.so.6
ELF	7dd7c000-7dd8c000	Deferred        libxi.so.6
ELF	7dd8c000-7dd90000	Deferred        libxcomposite.so.1
ELF	7dd90000-7dd9b000	Deferred        libxrandr.so.2
ELF	7dd9b000-7dda6000	Deferred        libxrender.so.1
ELF	7dda6000-7ddac000	Deferred        libxxf86vm.so.1
ELF	7ddac000-7ddce000	Deferred        libxcb.so.1
ELF	7ddce000-7df02000	Deferred        libx11.so.6
ELF	7df02000-7df15000	Deferred        libxext.so.6
ELF	7df21000-7df3a000	Deferred        libz.so.1
ELF	7df3a000-7dfcc000	Deferred        winex11<elf>
  \-PE	7df40000-7dfcc000	\               winex11
ELF	7dfcc000-7dff1000	Deferred        imm32<elf>
  \-PE	7dfd0000-7dff1000	\               imm32
ELF	7dff1000-7e008000	Deferred        wtsapi32<elf>
  \-PE	7e000000-7e008000	\               wtsapi32
ELF	7e008000-7e03e000	Deferred        wintrust<elf>
  \-PE	7e010000-7e03e000	\               wintrust
ELF	7e03e000-7e05b000	Deferred        jsproxy<elf>
  \-PE	7e040000-7e05b000	\               jsproxy
ELF	7e05b000-7e09c000	Deferred        winhttp<elf>
  \-PE	7e060000-7e09c000	\               winhttp
ELF	7e09c000-7e0b6000	Deferred        aclui<elf>
  \-PE	7e0a0000-7e0b6000	\               aclui
ELF	7e0b6000-7e132000	Deferred        shlwapi<elf>
  \-PE	7e0c0000-7e132000	\               shlwapi
ELF	7e132000-7e40e000	Deferred        shell32<elf>
  \-PE	7e140000-7e40e000	\               shell32
ELF	7e40e000-7e482000	Deferred        setupapi<elf>
  \-PE	7e420000-7e482000	\               setupapi
ELF	7e482000-7e5cb000	Deferred        oleaut32<elf>
  \-PE	7e4a0000-7e5cb000	\               oleaut32
ELF	7e5cb000-7e653000	Deferred        rpcrt4<elf>
  \-PE	7e5e0000-7e653000	\               rpcrt4
ELF	7e653000-7e7bd000	Deferred        ole32<elf>
  \-PE	7e670000-7e7bd000	\               ole32
ELF	7e7bd000-7e88f000	Deferred        crypt32<elf>
  \-PE	7e7d0000-7e88f000	\               crypt32
ELF	7e88f000-7e9c5000	Deferred        gdi32<elf>
  \-PE	7e8a0000-7e9c5000	\               gdi32
ELF	7e9c5000-7ebad000	Deferred        user32<elf>
  \-PE	7e9e0000-7ebad000	\               user32
ELF	7ebad000-7ecdc000	Deferred        comctl32<elf>
  \-PE	7ebc0000-7ecdc000	\               comctl32
ELF	7ecdc000-7ed5b000	Deferred        advapi32<elf>
  \-PE	7ecf0000-7ed5b000	\               advapi32
ELF	7ef5b000-7ef67000	Deferred        libnss_files.so.2
ELF	7ef67000-7ef73000	Deferred        libnss_nis.so.2
ELF	7ef73000-7ef8c000	Deferred        libnsl.so.1
ELF	7ef8c000-7ef95000	Deferred        libnss_compat.so.2
ELF	7ef95000-7efdb000	Deferred        libm.so.6
ELF	7efdb000-7efdf000	Deferred        libxinerama.so.1
ELF	7efdf000-7efe6000	Deferred        libxdmcp.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7382000-f738b000	Deferred        librt.so.1
ELF	f738c000-f7391000	Deferred        libdl.so.2
ELF	f7391000-f7542000	Dwarf           libc.so.6
ELF	f7542000-f755e000	Dwarf           libpthread.so.0
ELF	f7580000-f7584000	Deferred        libxau.so.6
ELF	f7584000-f7754000	Dwarf           libwine.so.1
ELF	f7756000-f7778000	Deferred        ld-linux.so.2
ELF	f7778000-f7779000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\user\.PlayOnLinux\tmp\AppManagerTmp\CreativeCloudSet-Up.exe
	[Z:\home\user\.PlayOnLinux\tmp\AppManagerTmp\CreativeCloudSet-Up.exe]
	00000036    0
	00000035    0
	00000030    0
	0000002f    0 <==
	00000009    0
0000000e services.exe
	[C:\windows\system32\services.exe]
	0000001e    0
	00000018    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000001d    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000020    0
	0000001f    0
	0000001c    0
0000002a explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
00000039 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
System information:
    Wine build: wine-2.17 (Staging)
    Platform: i386
    Version: Windows XP
    Host system: Linux
    Host version: 3.16.0-38-generic

**Comment by corbindavenport** [comment]
I'm getting the same error on Ubuntu 17.10 64bit. I'll look into solutions.

**Comment by corbindavenport** [comment]
This is due to a security feature in Ubuntu that conflicts with some Wine software. See the [Troubleshooting page](https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting) for instructions.
