### ISSUE TITLE
Create alternative installer that doesn't use PoL

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/creative-cloud-linux#12]
At some point in the future (after CC 2017 support is completed, if possible), a normal bash script should be made, which would install Creative Cloud to the user's existing Wine installation.

This would have a few advantages:
* It wouldn't require PlayOnLinux to be installed
* It could run sudo commands, which POL blocks for security reasons
* Once started, it could run in the background without any user interaction, until the user's Adobe ID is required (maybe it could [send notifications](https://wiki.archlinux.org/index.php/Desktop_notifications)?)

A PlayOnLinux version should still be maintained, for users that prefer that front-end.

**Comment by corbindavenport** [comment]
Another option for easy distribution: https://github.com/snapcrafters/steamforwindows

**Comment by tcitworld** [comment]
There's also https://winepak.org
