### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by luisfrancajr** [corbindavenport/creative-cloud-linux#13]
I tried installing but I'm having an error.

The whole walkthrough works, but when it comes to the end where I should put my Adobe login data, I can not connect. The form does not appear for me to be able to login. It's giving me a message to check the Firewall or to check the date and time on my computer.

I'm using Ubuntu 17.10, with Wine and Play on Linux updated.

**Comment by corbindavenport** [comment]
Can you try running the commands in the 'Install error at 3%' section of [the Troubleshooting page](https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting)? It's probably a security feature in Ubuntu conflicting with Wine.

**Comment by luisfrancajr** [comment]
I tried now. But after doing what you asked the wine stopped working. When it arrives in the part to create the virtual drive gives an error. It says wine has stopped working.

**Comment by luisfrancajr** [comment]
Error in POL_Wine

**Comment by corbindavenport** [comment]
Try going to the list of installed Wine versions in PlayOnLinux, delete WIne 2.17-staging, and run the script again.

**Comment by luisfrancajr** [comment]
It worked, thank you !!
I'm having a problem, I can not install Fireworks and Adobe Extension Manager CS6 updates. Gives the error stating that an update failed, returning a code error U43M1D207.
I can use photoshop but I'm having problems with Fireworks. I can not move the elements. I can only copy, paste and change pages within the program.

**Comment by corbindavenport** [comment]
Looks like that is a bug in Wine, and it looks like it might be fixed soon: https://bugs.winehq.org/show_bug.cgi?id=39086

Since there's nothing I can do, I'm closing this. I'll add the suggestion about deleting the Wine version to the Troubleshooting page.
