### ISSUE TITLE
Missing Libraries after following troubleshooting. Ubuntu 17.10 64 bit.

### ISSUE THREAD

**Issue by Aykann** [corbindavenport/creative-cloud-linux#14]
After following troubleshooting page and executing: 
`sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wineserver`
`sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wine-preloader`
I am being prompet with this error after attempting to install it again: 

> /home/wojtek/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wine: error while loading shared libraries: libwine.so.1: cannot open shared object file: No such file or directory

**Comment by corbindavenport** [comment]
Try going to the list of installed Wine versions in PlayOnLinux, delete WIne 2.17-staging, and run the script again.

**Comment by corbindavenport** [comment]
I assume that fixed it for you, so I'm closing this issue. If you're still having problems, feel free to re-open it.

**Comment by jlxip** [comment]
I am having that same error.

**Comment by jlxip** [comment]
It magically fixed itself after reinstalling Playonlinux.
