### ISSUE TITLE
When using patch from Wiki, POL errors arive

### ISSUE THREAD

**Issue by AtzeDeVries** [corbindavenport/creative-cloud-linux#16]
My my installer was stuck at 2%. I found this (closed) issue
https://github.com/corbindavenport/creative-cloud-linux/issues/7

Which in the end suggest running this;
https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting#install-error-at-3

Now i have POL errors durinig install and install is fully broken. 

```
Error in POL_Wine
Wine seems to have crashed

If your program is running, just ignore this message
```

i am running archlinux (all packages up to date)

**Comment by corbindavenport** [comment]
Try running the script again, and when it asks you to Overwrite or Erase, check Erase.

**Comment by AtzeDeVries** [comment]
When rerunning the script, i have the same errors.

**Comment by AtzeDeVries** [comment]
Ok, found the issue. I didn't need the wiki patch. Only needed to install `lib32-gnutls` (this is on arch linux)

**Comment by corbindavenport** [comment]
Thanks for figuring it out, I'll add it to the Troubleshooting page.

**Comment by AtzeDeVries** [comment]
Thnx for creating this script!!

Op wo 15 nov. 2017 om 05:52 schreef Corbin Davenport <
notifications@github.com>:
