### ISSUE TITLE
PlayOnLinux5 Scripts

### ISSUE THREAD

**Issue by ovari** [corbindavenport/creative-cloud-linux#18]
Would you please list your script at:
[PlayOnLinux scripts](https://github.com/PhoenicisOrg/Scripts)
Thank you

**Comment by corbindavenport** [comment]
Is that in any way related to the official PlayOnLinux project? Or just a separate repository?

**Comment by ovari** [comment]
This is the official PlayOnLinux 5 project
http://wiki.playonlinux.com/index.php/Building_PlayOnLinux_5

When you click on
https://github.com/PlayOnLinux/POL-POM-5/wiki/Build
the link redirects to
https://github.com/PhoenicisOrg/POL-POM-5/wiki/Build
which is a PhoenicisOrg repository for Scripts
https://github.com/PhoenicisOrg/Scripts

It would be great if all your scripts where located at
https://github.com/PhoenicisOrg/Scripts

What do you think?

Thank you

**Comment by ovari** [comment]
Release of PlayOnLinux 5.0 alpha 1
https://www.playonlinux.com/en/comments-1354.html

Phoenicis PlayOnLinux and PlayOnMac 5 repository https://phoenicis.org/
https://github.com/PhoenicisOrg/phoenicis/
