### ISSUE TITLE
Unhandled exception: page fault on read access to 0x01382a4c in 32-bit code

### ISSUE THREAD

**Issue by thobjata** [corbindavenport/creative-cloud-linux#19]
I'm getting an error at about 14% of the Adobe CC installer. Here is the backtrace:
[backtrace.txt](https://github.com/corbindavenport/creative-cloud-linux/files/1562555/backtrace.txt)

I have done fix for install error at 3% for ubuntu, and the POL_wine fix, because I encountered both these errors the first couple of tries.

**Comment by corbindavenport** [comment]
A brand new version of the install script has been published, can you check if the new update fixes your problem? https://github.com/corbindavenport/creative-cloud-linux/blob/master/README.md

**Comment by webian** [comment]
Same problem here, tried today with latest script.
Here is my backtrace: [backtrace.txt](https://pastebin.com/UJhMtiRK)

**Comment by webian** [comment]
Just an update: I tried [the classic script](https://github.com/corbindavenport/creative-cloud-linux/tree/classic) and now "Adobe Application Manager" is installed and it opens but when I click on "Try" for Photoshop CC it gives me error "Installation Failed: Download error. Press Retry to try again or contact customer support. (404)".
Hitting "Retry" produces the same error.

Instead, I tried Illustrator CC (2015) and it's downloading it.

**Comment by davidhiendl** [comment]
I've experienced the same issue on Ubuntu and currently worked around this issue by installation an older version (17.0.2) which seems to work fine. Just the newer 19.x versions are having problems.

**Comment by seesemichaelj** [comment]
Also was receiving this issue installing Photoshop. Here is the backtrace:
https://gist.github.com/seesemichaelj/e7c48ad9e3ae2d5f06e159431b2ccc09

**Comment by seesemichaelj** [comment]
Thanks @davidhiendl! That also worked for me
