### ISSUE TITLE
Add support for Creative Cloud 2017

### ISSUE THREAD

**Issue by octoxan** [corbindavenport/creative-cloud-linux#2]
Is there any way to make this so the 2017 versions of apps show up, including Adobe XD which is missing entirely at the moment?

**Comment by corbindavenport** [comment]
As far as I know, the 2017 apps requires the newest Creative Cloud app, which I haven't figured out how to get working. Not sure if I'll be able to get something working, but I'll look into it.

**Comment by CorbsEditor** [comment]
WHAT?! NO XD 

REEEEEEEEEEEEEEEEEEEEEE

**Comment by corbindavenport** [comment]
Currently working on CC 2017 support on the dev branch: https://github.com/corbindavenport/creative-cloud-linux/tree/dev

**Comment by corbindavenport** [comment]
Support for Creative Cloud 2018 is now in the master branch.
