### ISSUE TITLE
How to run an installed application in AAM (Creative Cloud)?

### ISSUE THREAD

**Issue by TeroBlaZe** [corbindavenport/creative-cloud-linux#20]
Your suggestions

**Comment by corbindavenport** [comment]
After you download an app, you can add a PlayOnLinux shortcut for it by clicking Adobe Application Manager in the app list, clicking **Configure**, and clicking **Make a new shortcut from this virtual drive**. Then look for the app, like Photoshop.exe, and add it.

**Comment by olantrust** [comment]
Would be useful to put this in the main wiki page for other users perhaps?

**Comment by corbindavenport** [comment]
It says it during the install, but yeah, I could put this somewhere else.
