### ISSUE TITLE
Got the following error while installing on Ubuntu 17.04

### ISSUE THREAD

**Issue by demis001** [corbindavenport/creative-cloud-linux#23]
@corbindavenport 

I have followed your youtub video and got the following error when installing Adobe DC

`Exit Code: 7
Please see specific errors below for troubleshooting. For example,  ERROR: DW003, DW071 ...

-------------------------------------- Summary --------------------------------------

 - 0 fatal error(s), 2 error(s) 

----------- Payload: Adobe Acrobat DC 18.9.20044.0 Adobe Acrobat\Setup.exe_18.009.20044 -----------

ERROR: DW071: 

ERROR: DW003: Third party payload installer Adobe Acrobat\Setup.exe failed with exit code: 1603

-------------------------------------------------------------------------------------
`

Best

**Comment by corbindavenport** [comment]
A brand new version of the install script has been published, can you check if the new update fixes your problem? https://github.com/corbindavenport/creative-cloud-linux/blob/master/README.md
