### ISSUE TITLE
Add support for Lightroom, Adobe XD, and other newer apps

### ISSUE THREAD

**Issue by unhammer** [corbindavenport/creative-cloud-linux#25]
In case it's relevant for anyone here, here's my current status (trying and failing) on getting LR6 Classic to run on Wine:
https://www.playonlinux.com/en/topic-15708.html
I'd be grateful for any help or tips :-)

(Would it make sense to include non-cloud scripts in this repo too?)

**Comment by corbindavenport** [comment]
I'd definitely like to get Lightroom 6+ working at some point, even the new installer will only let you download v5.

As for including non-cloud scripts in this repo, I think it would make more sense for someone to make a new repo with their script, and I could link it in this one.

**Comment by unhammer** [comment]
OK, the work-in-progress script is at https://github.com/unhammer/lr6-linux

**Comment by karanrajpal14** [comment]
Any update on this? Is the updated script buggy or can it be used to get XD working?

**Comment by corbindavenport** [comment]
All versions of the script no longer work, see #52.

**Comment by karanrajpal14** [comment]
@corbindavenport oops, sorry to hear that. Hope someone cracks this someday. Thanks!
