### ISSUE TITLE
Program error (Photoshop)

### ISSUE THREAD

**Issue by renatorocha1** [corbindavenport/creative-cloud-linux#26]
When I try to open photoshop.

```
Ubuntu: 16.04 LTS
Processor: Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 
Graphics: GeForce 920M/PCIe/SSE2
OS type: 64-bit
```
illustrator is working, thank you very much.

Any clues?

Unhandled exception: 0xc06d007f in 32-bit code (0x7b440872).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b440872 ESP:0033ef94 EBP:0033f008 EFLAGS:00000202(   - --  I   - - - )
 EAX:7b42b4ed EBX:7b645bc8 ECX:00000004 EDX:0033efb4
 ESI:00000001 EDI:0aa00000
Stack dump:
0x0033ef94:  0033f070 00000004 7bd174c0 c06d007f
0x0033efa4:  00000000 00000000 7b440872 00000001
0x0033efb4:  0033f038 0033efe0 0551e470 0033efe0
0x0033efc4:  0551e470 0033f018 7b461957 0551e470
0x0033efd4:  0aa00000 7b42b45d 7b461957 c000007a
0x0033efe4:  0033eff8 00000000 0033eff4 08580340
Backtrace:
=>0 0x7b440872 in kernel32 (+0x20872) (0x0033f008)
  1 0x04884a70 in photoshop (+0x4484a6f) (0x0033f068)
  2 0x0488f85d in photoshop (+0x448f85c) (0x0033f0ac)
  3 0x0323e2cf in photoshop (+0x2e3e2ce) (0x0033f0c8)
  4 0x0323debd in photoshop (+0x2e3debc) (0x0033f0f8)
  5 0x0323e476 in photoshop (+0x2e3e475) (0x0033f120)
  6 0x0323dd1d in photoshop (+0x2e3dd1c) (0x0033f19c)
  7 0x0323f3ec in photoshop (+0x2e3f3eb) (0x0033f1b8)
  8 0x033b0b93 in photoshop (+0x2fb0b92) (0x0033f434)
  9 0x033b15d7 in photoshop (+0x2fb15d6) (0x0033f448)
  10 0x03ea2132 in photoshop (+0x3aa2131) (0x0033f458)
  11 0x03ea4a2b in photoshop (+0x3aa4a2a) (0x0033f470)
  12 0x03ea3d8a in photoshop (+0x3aa3d89) (0x0033f748)
  13 0x03f80d0a in photoshop (+0x3b80d09) (0x0033f778)
  14 0x034e1667 in photoshop (+0x30e1666) (0x0033f974)
  15 0x046eaad9 in photoshop (+0x42eaad8) (0x0033fdc4)
  16 0x04c46828 in photoshop (+0x4846827) (0x0033fe10)
  17 0x7b4696a9 call_process_entry+0x18() in kernel32 (0x0033fe38)
  18 0x7b46ad14 in kernel32 (+0x4ad13) (0x0033fe98)
  19 0x7bcad834 call_thread_func_wrapper+0xb() in ntdll (0x0033fec8)
  20 0x7bcb0fdd in ntdll (+0x70fdc) (0x0033ffa8)
  21 0x7bcad812 RtlRaiseException+0x49() in ntdll (0x0033ffc8)
  22 0x7bc7b0ea call_dll_entry_point+0x5a9() in ntdll (0x0033ffe8)
  23 0xf7d2979d wine_call_on_stack+0x1c() in libwine.so.1 (0x00000000)
  24 0xf7d2985b wine_switch_to_stack+0x2a() in libwine.so.1 (0xffc08098)
  25 0x7bc8356a LdrInitializeThunk+0x4d9() in ntdll (0xffc08188)
  26 0x7b4719c0 __wine_kernel_init+0x98f() in kernel32 (0xffc090b8)
  27 0x7bc83c9a __wine_process_init+0x1b9() in ntdll (0xffc09138)
  28 0xf7d27b82 wine_init+0x2a1() in libwine.so.1 (0xffc09198)
  29 0x7c000d7b main+0x7a() in <wine-loader> (0xffc095e8)
  30 0xf7b61637 __libc_start_main+0xf6() in libc.so.6 (0x00000000)
0x7b440872: movl	0xfffffff4(%ebp),%ecx
Modules:
Module	Address			Debug info	Name (179 modules)
PE	  340000-  39a000	Deferred        cggl
PE	  3a0000-  3e6000	Deferred        tbb
PE	  400000- 6e50000	Export          photoshop
PE	 6e50000- 7229000	Deferred        libmmd
PE	 7230000- 7300000	Deferred        adobe_caps
PE	 7300000- 7333000	Deferred        manta
PE	 7340000- 73f1000	Deferred        vulcancontrol
PE	 7400000- 74cf000	Deferred        vulcanmessage5
PE	 74d0000- 7516000	Deferred        ahclient
PE	 7520000- 75cc000	Deferred        axedomcore
PE	 75d0000- 7a1c000	Deferred        mps
PE	 7a20000- 7b41000	Deferred        aide
PE	 7b50000- 7f69000	Deferred        plugplugowl
PE	 7f70000- 80fa000	Deferred        adobeowl
PE	 8100000- 81a3000	Deferred        extendscript
PE	 81b0000- 8242000	Deferred        sccore
PE	 87d0000- 880e000	Deferred        tbbmalloc
PE	 9280000- 93f2000	Deferred        adobelinguistic
PE	 9c20000- 9da5000	Deferred        photoshop
PE	 9db0000- a035000	Deferred        psviews
PE	 a040000- a042000	Deferred        psart
PE	 aa00000- abbe000	Deferred        amtlib
PE	 b420000- b430000	Deferred        fastcore.8bx
PE	 b430000- b44f000	Deferred        plugin
PE	 b450000- b470000	Deferred        psdx.8bi
PE	 cf20000- d0bb000	Deferred        logsession
PE	 d0c0000- d191000	Deferred        mmxcore.8bx
PE	 d1a0000- d8ad000	Deferred        svml_dispmd
PE	 d9c0000- da40000	Deferred        multiprocessor support.8bx
PE	 e7e0000- e894000	Deferred        adobexmp
PE	 e9b0000- eb38000	Deferred        imslib
PE	10000000-100a1000	Deferred        adbepm
PE	16000000-1600a000	Deferred        dnssd
PE	4a800000-4a8dc000	Deferred        icucnv40
PE	4ad00000-4ba47000	Deferred        icudt40
PE	4ec50000-4edfb000	Deferred        gdiplus
PE	4fad0000-51375000	Deferred        camera raw.8bi
PE	6a000000-6a63a000	Deferred        cg
ELF	7a800000-7a93a000	Deferred        opengl32<elf>
  \-PE	7a820000-7a93a000	\               opengl32
ELF	7b400000-7b7f6000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b7f6000	\               kernel32
ELF	7bc00000-7bd2b000	Dwarf           ntdll<elf>
  \-PE	7bc40000-7bd2b000	\               ntdll
ELF	7c000000-7c003000	Dwarf           <wine-loader>
ELF	7ca98000-7cacf000	Deferred        libtxc_dxtn.so
ELF	7cb36000-7cb6e000	Deferred        uxtheme<elf>
  \-PE	7cb40000-7cb6e000	\               uxtheme
ELF	7cb6e000-7cb75000	Deferred        libxfixes.so.3
ELF	7cb75000-7cb81000	Deferred        libxcursor.so.1
ELF	7cbdc000-7cc06000	Deferred        libexpat.so.1
ELF	7cc06000-7cc4f000	Deferred        libfontconfig.so.1
ELF	7cc4f000-7cceb000	Deferred        libfreetype.so.6
ELF	7cceb000-7ccfe000	Deferred        libxi.so.6
ELF	7ccfe000-7cd02000	Deferred        libxcomposite.so.1
ELF	7cd02000-7cd0f000	Deferred        libxrandr.so.2
ELF	7cd0f000-7cd1b000	Deferred        libxrender.so.1
ELF	7cd1b000-7cd22000	Deferred        libxxf86vm.so.1
ELF	7cd22000-7cd26000	Deferred        libxinerama.so.1
ELF	7cd26000-7cd2d000	Deferred        libxdmcp.so.6
ELF	7cd2d000-7cd53000	Deferred        libxcb.so.1
ELF	7cd53000-7ce9e000	Deferred        libx11.so.6
ELF	7ce9e000-7ceb3000	Deferred        libxext.so.6
ELF	7ceb3000-7cf45000	Deferred        winex11<elf>
  \-PE	7cec0000-7cf45000	\               winex11
ELF	7d045000-7d05b000	Deferred        libgpg-error.so.0
ELF	7d05b000-7d0d2000	Deferred        libpcre.so.3
ELF	7d0d2000-7d0ef000	Deferred        libgcc_s.so.1
ELF	7d0ef000-7d19e000	Deferred        libgcrypt.so.20
ELF	7d19e000-7d1c4000	Deferred        liblzma.so.5
ELF	7d1c4000-7d1ea000	Deferred        libselinux.so.1
ELF	7d1ea000-7d278000	Deferred        libsystemd.so.0
ELF	7d278000-7d281000	Deferred        libffi.so.6
ELF	7d281000-7d29a000	Deferred        libresolv.so.2
ELF	7d29a000-7d29f000	Deferred        libkeyutils.so.1
ELF	7d29f000-7d2f9000	Deferred        libdbus-1.so.3
ELF	7d2f9000-7d385000	Deferred        libgmp.so.10
ELF	7d385000-7d3ba000	Deferred        libhogweed.so.4
ELF	7d3ba000-7d3f7000	Deferred        libnettle.so.6
ELF	7d3f7000-7d40c000	Deferred        libtasn1.so.6
ELF	7d40c000-7d440000	Deferred        libidn.so.11
ELF	7d440000-7d4a1000	Deferred        libp11-kit.so.0
ELF	7d4a1000-7d4ae000	Deferred        libkrb5support.so.0
ELF	7d4ae000-7d4df000	Deferred        libk5crypto.so.3
ELF	7d4df000-7d5b5000	Deferred        libkrb5.so.3
ELF	7d5b5000-7d5c9000	Deferred        libavahi-client.so.3
ELF	7d5c9000-7d721000	Deferred        libgnutls.so.30
ELF	7d721000-7d773000	Deferred        libgssapi_krb5.so.2
ELF	7d773000-7d7fa000	Deferred        libcups.so.2
ELF	7d7fa000-7d956000	Deferred        wined3d<elf>
  \-PE	7d810000-7d956000	\               wined3d
ELF	7d956000-7da28000	Deferred        crypt32<elf>
  \-PE	7d960000-7da28000	\               crypt32
ELF	7da28000-7dd04000	Deferred        shell32<elf>
  \-PE	7da40000-7dd04000	\               shell32
ELF	7dd25000-7dd29000	Deferred        libxau.so.6
ELF	7dd29000-7dd37000	Deferred        libavahi-common.so.3
ELF	7dd58000-7dd7d000	Deferred        imm32<elf>
  \-PE	7dd60000-7dd7d000	\               imm32
ELF	7dd7d000-7dda7000	Deferred        dxgi<elf>
  \-PE	7dd80000-7dda7000	\               dxgi
ELF	7dda7000-7ddc7000	Deferred        cabinet<elf>
  \-PE	7ddb0000-7ddc7000	\               cabinet
ELF	7ddc7000-7ddef000	Deferred        mpr<elf>
  \-PE	7ddd0000-7ddef000	\               mpr
ELF	7ddef000-7de08000	Deferred        libz.so.1
ELF	7de08000-7de85000	Deferred        wininet<elf>
  \-PE	7de10000-7de85000	\               wininet
ELF	7de85000-7dfb4000	Deferred        comctl32<elf>
  \-PE	7de90000-7dfb4000	\               comctl32
ELF	7dfb4000-7dfce000	Deferred        aclui<elf>
  \-PE	7dfc0000-7dfce000	\               aclui
ELF	7dfce000-7e073000	Deferred        urlmon<elf>
  \-PE	7dfe0000-7e073000	\               urlmon
ELF	7e073000-7e18d000	Deferred        msi<elf>
  \-PE	7e080000-7e18d000	\               msi
ELF	7e18d000-7e27b000	Deferred        msvcr120<elf>
  \-PE	7e1b0000-7e27b000	\               msvcr120
ELF	7e27b000-7e3a8000	Deferred        msvcp120<elf>
  \-PE	7e2c0000-7e3a8000	\               msvcp120
ELF	7e3a8000-7e3eb000	Deferred        winspool<elf>
  \-PE	7e3b0000-7e3eb000	\               winspool
ELF	7e3eb000-7e534000	Deferred        oleaut32<elf>
  \-PE	7e400000-7e534000	\               oleaut32
ELF	7e534000-7e551000	Deferred        jsproxy<elf>
  \-PE	7e540000-7e551000	\               jsproxy
ELF	7e551000-7e592000	Deferred        winhttp<elf>
  \-PE	7e560000-7e592000	\               winhttp
ELF	7e592000-7e5d1000	Deferred        ws2_32<elf>
  \-PE	7e5a0000-7e5d1000	\               ws2_32
ELF	7e5d1000-7e64d000	Deferred        shlwapi<elf>
  \-PE	7e5e0000-7e64d000	\               shlwapi
ELF	7e64d000-7e69a000	Deferred        liblcms2.so.2
ELF	7e69a000-7e6ba000	Deferred        mscms<elf>
  \-PE	7e6a0000-7e6ba000	\               mscms
ELF	7e6ba000-7e6f3000	Deferred        glu32<elf>
  \-PE	7e6c0000-7e6f3000	\               glu32
ELF	7e6f3000-7e77b000	Deferred        rpcrt4<elf>
  \-PE	7e700000-7e77b000	\               rpcrt4
ELF	7e77b000-7e8e5000	Deferred        ole32<elf>
  \-PE	7e790000-7e8e5000	\               ole32
ELF	7e8e5000-7e964000	Deferred        advapi32<elf>
  \-PE	7e8f0000-7e964000	\               advapi32
ELF	7e964000-7ea9a000	Deferred        gdi32<elf>
  \-PE	7e970000-7ea9a000	\               gdi32
ELF	7ea9a000-7ec82000	Deferred        user32<elf>
  \-PE	7eab0000-7ec82000	\               user32
ELF	7ec82000-7ed45000	Deferred        msvcrt<elf>
  \-PE	7eca0000-7ed45000	\               msvcrt
ELF	7ef45000-7ef58000	Deferred        libnss_files.so.2
ELF	7ef58000-7ef65000	Deferred        libnss_nis.so.2
ELF	7ef65000-7ef80000	Deferred        libnsl.so.1
ELF	7ef80000-7ef8a000	Deferred        libnss_compat.so.2
ELF	7ef8a000-7efdf000	Deferred        libm.so.6
ELF	7efe1000-7efe6000	Deferred        libcom_err.so.2
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f74b3000-f7600000	Deferred        actxprxy<elf>
  \-PE	f74e0000-f7600000	\               actxprxy
ELF	f775c000-f776f000	Deferred        psapi<elf>
  \-PE	f7760000-f776f000	\               psapi
ELF	f776f000-f77b6000	Deferred        usp10<elf>
  \-PE	f7780000-f77b6000	\               usp10
ELF	f7962000-f798c000	Deferred        iphlpapi<elf>
  \-PE	f7970000-f798c000	\               iphlpapi
ELF	f798c000-f7a00000	Deferred        setupapi<elf>
  \-PE	f79a0000-f7a00000	\               setupapi
ELF	f7b07000-f7b1a000	Deferred        msimg32<elf>
  \-PE	f7b10000-f7b1a000	\               msimg32
ELF	f7b1a000-f7b40000	Deferred        sti<elf>
  \-PE	f7b20000-f7b40000	\               sti
ELF	f7b44000-f7b49000	Deferred        libdl.so.2
ELF	f7b49000-f7cff000	Dwarf           libc.so.6
ELF	f7cff000-f7d1c000	Deferred        libpthread.so.0
ELF	f7d1c000-f7eec000	Dwarf           libwine.so.1
ELF	f7eec000-f7f34000	Deferred        libesets_pac.so
ELF	f7f37000-f7f40000	Deferred        librt.so.1
ELF	f7f57000-f7f7c000	Deferred        ld-linux.so.2
ELF	f7f7f000-f7f80000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Program Files\Adobe\Adobe Photoshop CC 2015 (32 Bit)\Photoshop.exe
	["C:\Program Files\Adobe\Adobe Photoshop CC 2015 (32 Bit)\Photoshop.exe"]
	00000054    0
	00000053    0
	00000052    0
	0000004d    0
	0000004c    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000009    0 <==
0000000e services.exe
	[C:\windows\system32\services.exe]
	00000046    0
	00000029    0
	00000021    0
	00000013    0
	00000010    0
	0000000f    0
00000011 AGSService.exe
	["C:\Program Files\Common Files\Adobe\AdobeGCClient\AGSService.exe"]
	0000003e    0
	0000001f    0
	0000001e    0
	0000001a    0
	00000019    0
	00000016    0
	00000012    0
0000001c winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000028    0
	00000023    0
	00000022    0
	0000001d    0
00000026 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	0000002b    0
	0000002a    0
	00000027    0
00000035 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000039    0
	00000038    0
	00000037    0
	00000036    0
00000044 svchost.exe
	[C:\windows\system32\svchost.exe -k imgsvc]
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000045    0
00000057 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000005b    0
	0000005a    0
	00000059    0
	00000058    0
System information:
    Wine build: wine-2.17 (Staging)
    Platform: i386
    Version: Windows Server 2008 R2
    Host system: Linux
    Host version: 4.13.0-32-generic

**Comment by corbindavenport** [comment]
A brand new version of the install script has been published, can you check if the new update fixes your problem? https://github.com/corbindavenport/creative-cloud-linux/blob/master/README.md

**Comment by kszere** [comment]
When run Photoshop, I see only black window. How fix?
