### ISSUE TITLE
gui is flickering

### ISSUE THREAD

**Issue by KuntzeM** [corbindavenport/creative-cloud-linux#3]
Hi,
thank you so much!!!

If I select menus or zooming in the picture, than my photoshop gui is flickering.
Do you have the same problem?

another question:
Do you have experience with wine 64bit. I tried to run lightroom cc. But with no success. There exists only a 64bit version.

regards
Mathias

**Comment by corbindavenport** [comment]
The flickering may be related to #1, I'll see if I can replicate it and maybe find a fix. As for 64-bit, PlayOnLinux glitched out for me every time I tried to make a 64-bit prefix, but I'll look into it again at some point.

**Comment by KuntzeM** [comment]
ok, the problem is solved.
I'm using Linux mint with a autohide taskbar. The gui is flickering on this monitor. It jumps a little bit up and down. On my second screen with a fixed taskbar is it no flickering.

I changed to wine 2.18 too.
