### ISSUE TITLE
Camera RAW Plugin (official Adobe Photoshop plugin)

### ISSUE THREAD

**Issue by delphir-com** [corbindavenport/creative-cloud-linux#32]
Camera RAW hangs up when you move the mouse over the bottom line buttons (Done/Open image/Cancel)

Ubuntu 16.04, 64bit, 4.15.2-041502-generic #201802072230
PlayOnLinux 4.2.10

```
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:shell:IShellBrowser_fnOnViewWindowActive stub, 0xb6739f0 (0x1970c758)
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos
fixme:win:GetPhysicalCursorPos (0x33d97c) semi-stub: forwarding to GetCursorPos

<<<<<<<<<<<<<<<<<< Mouse Move over the bottom line

fixme:kernelbase:AppPolicyGetThreadInitializationType 0xfffffffa, 0xd2ae9bc
fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 2
fixme:win:LockWindowUpdate (0x170048), partial stub!
fixme:win:LockWindowUpdate ((nil)), partial stub!
fixme:ole:NdrCorrelationInitialize (0x33ef94, 0x33f070, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationInitialize (0x21b6e214, 0x21b6e2f0, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationFree (0x21b6e214): stub
fixme:ole:NdrCorrelationFree (0x33ef94): stub
fixme:ole:NdrCorrelationInitialize (0x33ef94, 0x33f070, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationInitialize (0x21c6e214, 0x21c6e2f0, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationFree (0x21c6e214): stub
fixme:ole:NdrCorrelationFree (0x33ef94): stub
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:gdiplus:GdipGetLineSpacing ignoring style
fixme:ole:NdrCorrelationInitialize (0xd1e484, 0xd1e560, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationInitialize (0x21b6e214, 0x21b6e2f0, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationFree (0x21b6e214): stub
fixme:ole:NdrCorrelationFree (0xd1e484): stub
fixme:ole:NdrCorrelationInitialize (0xd1e484, 0xd1e560, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationInitialize (0x21c6e214, 0x21c6e2f0, 1024, 0x0): semi-stub
fixme:ole:NdrCorrelationFree (0x21c6e214): stub
fixme:ole:NdrCorrelationFree (0xd1e484): stub
fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
```

**Comment by delphir-com** [comment]
Attaching a sample RAW file. Dragging it into PS will force to open Camera RAW window.
[sample.zip](https://github.com/corbindavenport/creative-cloud-linux/files/1749857/sample.zip)

**Comment by paulcarroty** [comment]
@delphir-com PS 19.0.1, wine 3.2

![screenshot from 2018-03-01 11-13-09](https://user-images.githubusercontent.com/1550705/36836346-f3e77c02-1d30-11e8-8bf6-9b34ae6a921d.png)

**Comment by delphir-com** [comment]
No way to go without switching between windows? It is really annoying if you need to handle more than one image.

**Comment by delphir-com** [comment]
Actually the same problem applies to "File -> Export -> Save for web" window

**Comment by corbindavenport** [comment]
This sounds like a Wine bug (hence the "fixme" errors), not something I can fix with the script. I recommend filing a bug on the Wine project: https://bugs.winehq.org/

**Comment by keybreak** [comment]
@corbindavenport 
Just wanted to point it out - happens on this older parts of Photoshop like RAW / Save for web because of tooltip which fails to show when you hover on buttons / icons...

Maybe you'll get some winetricks idea.
I have no clue what possibly could cause just simple tooltip o crash whole interface, maybe some font missing?

**Comment by JiPRA** [comment]
This is a very annoying problem that hampers the usability of CameraRAW more than one could possibly believe. But lo and behold, ladies and gentlemen, there is a simple fix for this :grin:

Open Wine configuration utility (winecfg), switch to "Graphics" tab and uncheck the following checkboxes:

[&nbsp;&nbsp;&nbsp;] Allow the window manager to decorate the windows
[&nbsp;&nbsp;&nbsp;] Allow the window manager to control the windows

Apply the settings, start Photoshop and be productive with CameraRAW on Linux.
