### ISSUE TITLE
Error 202 when Setting Up Creative Cloud (Xubuntu 17.10)

### ISSUE THREAD

**Issue by data4pass** [corbindavenport/creative-cloud-linux#33]
The error dialog box indicates that it could be caused by insufficient storage space. I have ~28.2 GB of disk space left in ~/

Is there anything that can be done about this? Or do I just need more storage space to perform the installation? 

Thank you for the help.

**Comment by corbindavenport** [comment]
The installer definitely doesn't need or use that much space. I'm not sure what's going on there, maybe I can fire up a Xubuntu VM and see if I can duplicate it.

**Comment by AldyAhsn** [comment]
Hi. It happened to me also. I use Linux Mint (No VM) and still have 60 Gb remaining. After showing the error then i get POL_Wine error.

**Comment by AncalagonTheBlack** [comment]
Got the same error on linux mint 18.3 64bit

**Comment by corbindavenport** [comment]
I also got another email confirming this issue. Still trying to figure out a solution.

**Comment by walidhalabi** [comment]
Thanks Corbin.

Same on Ubuntu 18.04, happy to provide more info.

The installer crashed for me twice for different reasons, then on the third time this popped up.

**Comment by corbindavenport** [comment]
Merging this into #52.
