### ISSUE TITLE
the installer stop at 5% on ubuntu 17.10

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [corbindavenport/creative-cloud-linux#35]
https://imgur.com/a/OlxOs

**Comment by corbindavenport** [comment]
Did you try the Ubuntu install error troubleshooting step? https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting#install-error-at-3-ubuntu

**Comment by ejabu** [comment]
as for me, I tried on Kubuntu 18.04

![image](https://user-images.githubusercontent.com/2019630/42028041-68c69f7c-7af5-11e8-993a-8ad26efa01d7.png)

Previously it stuck on 5%. But after I tried to manage security exceptions as noted in "Install error at 3% (Ubuntu)", it progressed until 6% then stopped.

**Comment by corbindavenport** [comment]
Can both of you try the latest version of the install script? It now uses the offline installer package, so all the downloading is done by Linux instead of through Wine.

**Comment by ejabu** [comment]
Sure, will do

**Comment by phillipesouza** [comment]
I'm using the lastest script, and tried the classic and none off them worked on ubuntu 18.04, what can I do?

**Comment by corbindavenport** [comment]
I'm closing all issues besides #52, because I think everything else is stemming from that one bug.
