### ISSUE TITLE
Is it possible to run Adobe XD installer?

### ISSUE THREAD

**Issue by Syjgin** [corbindavenport/creative-cloud-linux#36]
After successfully installation via you script, I was not able to see XD download button. Is it possible to run it's separate installer via modification of script, or this is not supported for now? If this can be done via modification of script, I'm ready to pay you for this work

**Comment by corbindavenport** [comment]
At the moment, Adobe XD can't be installed. It requires a 64-bit installation ([more info](https://helpx.adobe.com/xd/system-requirements.html)), but this script creates a 32-bit install for the best possible compatibility.

Once the script switches to 64-bit, Adobe XD might work.
