### ISSUE TITLE
Photoshop - "Missing closing quotation mark in string" when creating new Document

### ISSUE THREAD

**Issue by metinkale38** [corbindavenport/creative-cloud-linux#39]
Hey, 
i am on a newly installed Ubuntu 18.04 with CPU Intel i7-5500U and Geforce 820M.

Steps i did:
1) Install Photoshop/Illustrator/InDesign (installation worked fine)
2) Started Photoshop
3) tried to create a new document with default configuration
4) got Error Dialog:
"Vorgang konnte nicht ausgeführt werden. (could not perform action)
Missing closing quotation mark in string"
5) installed NVIDIA drivers and retried, same issue

It does not crash, i only get this error
Opening existing PSD works.

**Comment by HirotakaTech** [comment]
Same

**Comment by corbindavenport** [comment]
I don't think this is something I can do anything about, it's a WINE bug. I recommend filing a bug report with them: https://bugs.winehq.org/
