### ISSUE TITLE
Unimplemented function KERNEL32.dll.GetQueuedCompletionStatusEx

### ISSUE THREAD

**Issue by seesemichaelj** [corbindavenport/creative-cloud-linux#43]
I get this Program Error on startup. You can find the backtrace here: https://gist.github.com/seesemichaelj/82acc4669f691f4f7f70f7596604af44

- elementary OS 0.4.1 Loki (based off Ubuntu 16.04)
- PlayOnLinux 4.2.12
- Downloaded the script in `master` branch today

The program does startup and I can login. Seems like I can't install applications (nothing happens when I click the install button)

**Comment by seesemichaelj** [comment]
Tried purging all instances of wine and running the script again. I did receive the attached error at first. I get a different screen telling me that it crashed and to run it in debug. Ran it in debug, still got the crash warning, but CC still logged in. I was able to press the "Install" button, and it seemed to start downloading until I received another error:
`Unhandled exception: page fault on read access to 0x00000170 in 32-bit code (0x0909fdf7).`

Seems to be stuck on 0%

**Comment by seesemichaelj** [comment]
This is probably two separate issues, but I'm not sure how to triage them. I wish I knew what to look for when ciphering through this stuff. I think this script is glorious if it works!

**Comment by seesemichaelj** [comment]
Looks like the page fault issue is being tracked in #19

**Comment by seesemichaelj** [comment]
Here is a Wine bug for this issue: https://bugs.winehq.org/show_bug.cgi?id=43878

**Comment by corbindavenport** [comment]
Hmm, looks like it's still not fixed in WINE. That's a bummer, I was hoping the update to a later Wine version would fix it. Maybe it still will, idk.

**Comment by seyhakann** [comment]
Have you tried download and installed externally?

**Comment by seesemichaelj** [comment]
I'm not sure where to find the link to download

**Comment by corbindavenport** [comment]
It's no longer possible to download Adobe applications without the Creative Cloud manager. Even if you download Photoshop or whatever from its own download page, it installs the same Creative Cloud app to handle updates.

**Comment by corbindavenport** [comment]
Merging this into #52, because that bug is blocking everything else.

**Comment by unfulvio** [comment]
Ok thanks. Additional info: the issues I have got with the script were a bit inconsistent. I never saw the 3% install error for instance. I did manage to have Creative Cloud installed, but it would always crash. Or, not install at all and bump into this error mentioned in this ticket. If you need further details or want me to try something please let me know. I'm on Fedora 28.
