### ISSUE TITLE
Crash at 20% (in the middle of downloading)

### ISSUE THREAD

**Issue by 1nikolas** [corbindavenport/creative-cloud-linux#44]
So I'm not here to ask for help. I actually figured it out by myself. I fixed it by installing this
`sudo apt-get install libp11-kit-gnome-keyring:i386`
You can add this on the Troubleshooting page
I'm on Ubuntu 16.04 
(I would edit the wiki by myself but github has no option to make pull requests for the wiki)

**Comment by corbindavenport** [comment]
Thanks, I've updated the wiki.
