### ISSUE TITLE
All alt + click actions are not working on Photoshop

### ISSUE THREAD

**Issue by 1nikolas** [corbindavenport/creative-cloud-linux#45]
When I hit alt I see the cursor changing to what it should be but when I click with the mouse it does nothing.. In other words I can't use clone stamp and healing brush. Does anyone know how to fix that?

**Comment by manfreed** [comment]
This is not a wine related issue. Alt+click (or drag) is most likely to be used by your window manager to drag windows around. You have to turn off this, or change it's shortcut. How to do this depends on your DE :)
