### ISSUE TITLE
Installer should say "Adobe Creative Cloud", not "Adobe Application Manager"

### ISSUE THREAD

**Issue by lovemoebius** [corbindavenport/creative-cloud-linux#47]
I installed Creative Cloud and Photoshop, both of them work perfectly.

Photoshop however only works when started from the Creative Cloud program. The readme for this scrips says that I'm supposed to start Adobe Application Manager to create a shortcut directly to the program, but I'm not entirely sure where this program is supposed to be.

I tried installing it from a separate download but it doesn't look like it's doing anything at all.

What should I be doing in this situation? What am I missing?

**Comment by corbindavenport** [comment]
The message about Application Manager is out of date. You have to select "Adobe Creative Cloud" in the PlayOnLinux app list, click the `Configure` button, and click `Make a new shortcut from this virtual drive`. Then find photoshop.exe on the list and select it.

**Comment by lovemoebius** [comment]
Ah sorry, my mistake then.
It's working perfectly now, thank you for making this.

**Comment by corbindavenport** [comment]
No worries, I just forgot to change that line. Glad it's working for you 😁

**Comment by corbindavenport** [comment]
This was fixed a while ago, but I forgot to close this bug.
