### ISSUE TITLE
Installer error/Unable to reach Adobe servers

### ISSUE THREAD

**Issue by 064xp** [corbindavenport/creative-cloud-linux#49]
When the Adobe installer runs, it goes to about 2% and then shows this error code 201
![screenshot from 2018-07-01 20-05-14](https://user-images.githubusercontent.com/38300554/42140932-b5217f1e-7d6a-11e8-9af2-8c9bbf4a3767.png)

Adobe's website states 
>Error 201, P201 | Occurs when the download is paused and when the server response is poor. See Network and connectivity issues, below.

Any idea what could be the cause?

**Comment by javierrebollo** [comment]
I have the same error :S

**Comment by javierrebollo** [comment]
Thaks @corbindavenport :D!! Now I can install but say this.
![screenshot from 2018-07-10 08-43-57](https://user-images.githubusercontent.com/2781905/42493493-88d5404e-841d-11e8-92fa-7fe1b5cf9bea.png)

**Comment by corbindavenport** [comment]
Can you try the troubleshooting step for 'Install error at 3%'? https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting#install-error-at-3-ubuntu

**Comment by JamesFromEdinburgh** [comment]
I have the same issue as Javierre.  I'm a Linux newbie running Mint.  I ran those scripts for "Install error at 3%" but I got "unable to set CAP_SETFCAP effective capability: Operation not permitted" after entering the third line, and I still get the adobe server error message.

**Comment by Chillstice** [comment]
While trying to use the latest dev version of the script on Linux Mint 19 and PlayOnLinux 4.2.12 I get: unable to reach adobe servers p206

**Comment by Polunom** [comment]
Getting the same error. Running the `setcap` commands work but running and re-installing the custom script produced multiple crashes. Arch 4.14

**Comment by Polunom** [comment]
Hmm, interesting. I reverted back to 7249d8324d3a4c2fda6a0cc20aa6d442e9ae331c and it seems to work. Probably an issue with the new CC application manager.

**Comment by corbindavenport** [comment]
I'm closing all issues besides #52, because I think everything else is stemming from that one bug.
