### ISSUE TITLE
icon for creative-cloud-linux

### ISSUE THREAD

**Issue by somratking420** [corbindavenport/creative-cloud-linux#50]
Hi @   corbindavenport  , I am a graphic designer, I want to help you in graphic design.

After I review your project, your project is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by luni3359** [comment]
Maybe post some ideas here, he may like one of them

**Comment by corbindavenport** [comment]
I don't think this project needs an icon, but your offer is very generous!
