### ISSUE TITLE
Cannot install any package

### ISSUE THREAD

**Issue by streambinder** [corbindavenport/creative-cloud-linux#54]
With Creative Cloud offline installer, got it installed and executing without any problem at all, except for the fact I can't install anything.
Once I run it via POL, an error popup appears:
![screen1](https://user-images.githubusercontent.com/7783188/43034569-107b8c46-8cdf-11e8-8cad-1125f4241115.png)

Anyway, Creative Cloud correctly starts.
If I click on any `Try` (or `Start`, `Install`), it doesn't do anything.
![screen2](https://user-images.githubusercontent.com/7783188/43034577-37e90272-8cdf-11e8-825c-3dd96b8415f4.png)

**Comment by rebeluarte** [comment]
i'm with the same error, if i found some fix, i tell u

**Comment by corbindavenport** [comment]
I'm fairly sure this is due to the same issue described in #52, so I'm closing this.
