### ISSUE TITLE
Stuck at "Waiting"

### ISSUE THREAD

**Issue by Noen99** [corbindavenport/creative-cloud-linux#56]
![issue](https://user-images.githubusercontent.com/42045516/43605580-14db2b48-9699-11e8-8206-80aae90de179.png)
The installation won't proceed. I have waited for maybe about an hour and there is no end in sight.

**Comment by corbindavenport** [comment]
The main issue is lack of internet connectivity, which is being discussed in #52 and #49. I'm trying to get CC working on a newer Wine version to fix the problem. I'll close this issue, since the main discussion is on those issues.
