### ISSUE TITLE
Classic version doesn't use CC 2015

### ISSUE THREAD

**Issue by AldyAhsn** [corbindavenport/creative-cloud-linux#57]
Hi. I installed this repo version using classic version. I expected it will install cc 2015. But what I saw is CS version. Is that normal?
![screenshot_2018-08-24_19-41-58](https://user-images.githubusercontent.com/3055063/44613987-e0f30480-a846-11e8-95c6-e4ee14dbe7f2.png)

**Comment by Nakxion** [comment]
Hey Can I Active This program by cracking or it's just for 3 days trail ?

**Comment by corbindavenport** [comment]
The specific app you're trying to install might not be available on Windows XP 32-bit systems, which is what the classic version runs in.
