### ISSUE TITLE
Creative Cloud app tab doesn't work

### ISSUE THREAD

**Issue by ShazerHD** [corbindavenport/creative-cloud-linux#59]
I get the following error when trying to go to the apps tab in the Creative Cloud app.

[backtrace.txt](https://github.com/corbindavenport/creative-cloud-linux/files/2342045/backtrace.txt)

**Comment by stencill** [comment]
Having the same error
[backtrace.txt](https://github.com/corbindavenport/creative-cloud-linux/files/2346120/backtrace.txt)

Ubuntu 18.04.1 LTS
Wine version 3.0
PlayOnLinux 4.2.12

Other tabs work fine but the most important 'Applications' tab seems to be loading forever and finally throwing some kind of error

**Comment by alvintheodora** [comment]
@corbindavenport @stencill @ShazerHD Hi, I also encountered similar error, have you got the workaround for this issue?

**Comment by Regularest** [comment]
On mint, same problem, I get repeated adobe service crashes, and eventually the program will claim it needs to be reinstalled. It appears the wine installer never actually finishes.

**Comment by Regularest** [comment]
[backtrace.txt](https://github.com/corbindavenport/creative-cloud-linux/files/2382103/backtrace.txt)
Im pretty sure this is the moment things go wrong.

**Comment by corbindavenport** [comment]
Bug report from @android4682: https://pastebin.com/tZq3v5aQ

**Comment by kirgene** [comment]
Having the same problem.

**Comment by rottenpants** [comment]
Same issue here, Ubuntu 18.04 LTS. The apps folder doens't load..

**Comment by rrfaria** [comment]
Adobe Creative Cloud  open but the app tab stay loading forever.

**Comment by corbindavenport** [comment]
Hey all, I've been incredibly busy with work lately and haven't had time to properly look into this. I'm hoping to get a Kubuntu partition set up on my desktop sometime soon, so I won't have to test in a slow VM anymore.

**Comment by rottenpants** [comment]
Even though I'm new to Linux (tired of Windows) I can try and test stuff if you want. I'm currently using Ubuntu 18.10 and cc for some reason doesn't load the apps.

Cheers

**Comment by corbindavenport** [comment]
I'm sure it's the same issue affecting everyone. Now whether it's something that can actually be fixed, either through updating Wine or adding more hacks, I have no idea.

**Comment by shan-hannadige** [comment]
> Same issue here, Ubuntu 18.04 LTS.
> Adobe Creative Cloud open but the app tab stay loading forever.
> 
> And after long time the app open a box to repair. It reinstall creative cloud but stay with the same issue.

This same issue for me! But on 16.04 LTS... @corbindavenport please keep us posted with any findings :)

**Comment by Isengo1989** [comment]
Same Error here - is there annother solution for PS on Ubuntu 18.04 :/ ?

**Comment by channelmobiledev** [comment]
Same happen on ubuntu 18.10 with a clean Play On Linux installation

**Comment by corbindavenport** [comment]
I'm closing all issues besides #52, because I think everything else is stemming from that one bug.
