### ISSUE TITLE
having trouble connectin the adobe cc app

### ISSUE THREAD

**Issue by ramirofb101** [corbindavenport/creative-cloud-linux#6]
it just stays loading , then it said "cannot conect retry?"
![screenshot from 2017-10-10 23-41-30](https://user-images.githubusercontent.com/24764327/31419871-9f0c932e-ae14-11e7-90d9-356756e8efaf.png)
[10/10/17 23:42:55] - Running wine-2.17-staging Creative Cloud.exe (Working directory : /home/ramiro/.PlayOnLinux/wineprefix/CreativeCloud/drive_c/Program Files/Adobe/Adobe Creative Cloud/ACC)
fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x401123, 0x612150, 0x612168) stub.
fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x5f92d8, 43) stub
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Black"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Black"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Bold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Bold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand ExtraBold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand ExtraBold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand ExtraLight"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand ExtraLight"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand Light"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand Light"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand SemiBold"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand SemiBold"!
fixme:font:get_outline_text_metrics failed to read face_nameW for font L"Khand SemiLight"!
fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Khand SemiLight"!
fixme:process:UnregisterApplicationRestart : stub
fixme:nls:GetThreadPreferredUILanguages 00000038, 0x32f9d8, 0x32f9e8 0x32f9dc
fixme:nls:get_dummy_preferred_ui_language (0x38 0x32f9d8 0x32f9e8 0x32f9dc) returning a dummy value (current locale)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000060)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000060)
fixme:process:RegisterApplicationRestart (L" /RestartByRestartManager:2C13AD5A-97CE-437e-A2BD-B571AA4060D0",0)
fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x10001123, 0x1005d090, 0x1005d0a8) stub.
fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x100571a8, 43) stub
fixme:ntdll:EtwEventUnregister (deadbeef) stub.
fixme:ntdll:EtwEventUnregister (0) stub.
fixme:ver:GetCurrentPackageId (0x32fd74 (nil)): stub
err:msxml:doparse Start tag expected, '<' not found
fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
err:msxml:doparse Start tag expected, '<' not found
err:msxml:doparse Start tag expected, '<' not found

**Comment by VladimirDev93** [comment]
I assume that you download the app from a link that is within the script.

Run the script again, and when you see a window prompt for the Adobe App Manager, click the "Download the file" but this time using Wine version `2.18`.

I had the exact same problem and found out that I should use Wine version `2.18` instead of `2.17-staging` because that's what was causing the problem.

**Comment by corbindavenport** [comment]
@ramirofb101 Looks like it's trying to install the newest Application Manager, instead of the one I've tested to work. Did you modify the script in any way, or use a different installer?

**Comment by VladimirDev93** [comment]
@corbindavenport  It's CC 2015

**Comment by ramirofb101** [comment]
Thanks for the help ! The installer that the script runed failed every time. So I followed the instructions for wine that were provided and worked perfectly.
