### ISSUE TITLE
Unable to reach Adobe servers P206

### ISSUE THREAD

**Issue by Chillstice** [corbindavenport/creative-cloud-linux#61]
While trying to use the dev script on Linux Mint 19 and PlayOnLinux 4.2.12 the Creative Cloud Installer gets to the login screen, but when the login button is pressed, the following error immediately appears:
![ccerror](https://user-images.githubusercontent.com/1124121/45332681-43c6ea00-b52f-11e8-9a8b-bd1feb95ec42.png)

**Comment by co5dt** [comment]
Same issue Manjaro 18.0.0

**Comment by corbindavenport** [comment]
I'm closing all issues besides #52, because I think everything else is stemming from that one bug.
