### ISSUE TITLE
Adobe Installer Crash - "OS does not meet the minimum system requirements for this installer."

### ISSUE THREAD

**Issue by lizardthunder** [corbindavenport/creative-cloud-linux#65]
Hi!

Love what you've done here; if I can get this installer working, it's going to make life a lot easier.

I'm having an issue when PlayOnLinux runs the actual Adobe Creative Cloud installer. It gets through installing wine 2.20, the Microsoft C++ libs, etc. just fine, and then consistently crashes part of the way through the Creative Cloud install. It gives an error box that says "We've encountered the following issues: OS does not meet the minimum system requirements for this installer. Windows 7 is the minimum required for installation. (Error code: 21)." I've attached a screenshot below.

This is of course a "correct" error, since I'm not running Windows 7...

I'm running Ubuntu 18.04.1 LTS, 64-bit. PlayOnLinux is version 4.2.12, downloaded from the Ubuntu repository. I've also attached the rest of the system specs, in case they matter.

Thanks!

![image](https://user-images.githubusercontent.com/9540015/47185073-73b99800-d2fa-11e8-8f1f-5b7502fe4991.png)

![image](https://user-images.githubusercontent.com/9540015/47184972-2b01df00-d2fa-11e8-96a2-7a844224d9ad.png)

**Comment by josejlpp** [comment]
I have the same issues in the Manjaro

**Comment by corbindavenport** [comment]
I'm closing all issues besides #52, because I think everything else is stemming from that one bug.
