### ISSUE TITLE
Unable to upgrade dated Adobe Creative Cloud 

### ISSUE THREAD

**Issue by blackoutworm** [corbindavenport/creative-cloud-linux#69]
Hi there. You closed my last issue and linked it to an unrelated one.
So here's the problem, during the installation of Adobe Creative Cloud, ACC is trying to upgrade to a later version. The version in your script (ACCCx4.5.0.331) is dated. It starts updating just fine, but after it gets to 9%, I'm getting this error "There seems to be a problem with the file download. For troubleshooting tips, please visit our customer support page (Error code 201)"..
So I I tried to install the latest version myself within the wine bottle. This didn't work either.
The program wouldn't even start.
So I replaced the old version with the new on in your script and re-ran it, which also didn't work.
I'm kinda out of options here. Not sure how to solve this.

**Comment by corbindavenport** [comment]
Yeah, I had that problem too when trying to manually run the latest installer .exe inside the PlayOnLinux drive. I've tried for hours upon hours to get the latest Creative Cloud running and it just isn't happening. Someone smarter than me will need to figure it out.

**Comment by corbindavenport** [comment]
Closed because Adobe broke this and I don't think there's a way to unbreak it. Getting the latest Creative Cloud to work (#52) is the only way forward.
