### ISSUE TITLE
stop at Initializing Installer 2%

### ISSUE THREAD

**Issue by yaro97** [corbindavenport/creative-cloud-linux#7]
![deepinscreenshot_select-area_20171022084913](https://user-images.githubusercontent.com/12781825/31857062-fd1940ee-b705-11e7-9a9b-a002daa047ca.png)

**Comment by autrimpo** [comment]
I have the same issue.

**Comment by officermeraz** [comment]
I have the same issue.  I think Adobe is blocking us from installing on Linux.  hmm. I hope someone can figure out a fix.

**Comment by officermeraz** [comment]
@autrimpo and @yaro97 I found out the problem.  So there's a security block preventing the download. Thank the gaming community for fixing this :smile: 
 
In terminal type:
cat /proc/sys/kernel/yama/ptrace_scope

If you get the output '1', that means the security feature is enabled.

To disable this, type in:

echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

You will be prompted for your password, as it requires root privileges to edit the file.

Now you can safely continue the installation. If your output was anything other than '1' to the first command, then this is not enabled on your system.

To enable this again later, simply type in:

echo 1 | sudo tee /proc/sys/kernel/yama/ptrace_scope

Let me know if this doesn't work.

**Comment by corbindavenport** [comment]
@officermeraz Do you know if there's a way a fix can be added to the script? I know PoL doesn't allow sudo commands.

**Comment by yaro97** [comment]
finally，i

**Comment by yaro97** [comment]
uh, finally, I use GIMP instead of PS.

**Comment by corbindavenport** [comment]
This could be the same issue described in #11. I'm looking into the best solution.

**Comment by corbindavenport** [comment]
Looks like @officermeraz's solution is the best possible workaround. I have added modified instructions to the new [Troubleshooting page](https://github.com/corbindavenport/creative-cloud-linux/wiki/Troubleshooting).

**Comment by dmsumon** [comment]
Whenever I try to use the script I found the following errors

![untitled2](https://user-images.githubusercontent.com/8942430/39885002-59bbc318-54ad-11e8-9cb6-09e3edd5729e.png)

According to the @officermeraz the command "echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope" didn't make any magic ... 

According to the  Troubleshooting page if I run the following two commands 

sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wineserver
sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wine-preloader

I get the following error outputs 

![untitled4](https://user-images.githubusercontent.com/8942430/39885319-1dd309be-54ae-11e8-9799-e5cbce0df5d1.png)

Please help @corbindavenport
