### ISSUE TITLE
AGMService.exe problem

### ISSUE THREAD

**Issue by joojisan** [corbindavenport/creative-cloud-linux#72]
Hello!
I have an issue at the end of the installation, after longing in CC account.
I receive AGMService.exe problem. The progress finished with the update of CC application and then it says a problem with CreativeCloud.exe.
So the installation loading and loading and can not finish...
Sorry if this is known issue, I could not find it.

**Comment by BakaSai** [comment]
Yep, same issue here.

**Comment by GuilhermeTokitaka** [comment]
Same issue too!

**Comment by corbindavenport** [comment]
Duplicate of #52
