### ISSUE TITLE
Error in main Adobe Creative Cloud bloqueou.

### ISSUE THREAD

**Issue by thborba** [corbindavenport/creative-cloud-linux#77]

**Comment by thborba** [comment]
![Captura de tela de 2020-01-29 09-32-39](https://user-images.githubusercontent.com/42552727/73357001-518f2380-427a-11ea-8848-c77cef59be9f.png)

**Comment by LuizFellype** [comment]
Same error here. 
Linux mint

**Comment by corbindavenport** [comment]
The script doesn't work for anyone right now, see #52.
