### ISSUE TITLE
Photoshop doesn't start anymore

### ISSUE THREAD

**Issue by chrisribal** [corbindavenport/creative-cloud-linux#9]
I've installed Photoshop with your script on a computer and a laptop. Both worked great, but unfortunately after one day photoshop seems to break and doesn't start anymore. When i try to start photoshop, an error message appears saying: "could not initialize Photoshop because of a program error.".

The PSErrorLog.txt seems to claim that it couldn't find or include a file:

> 2017:10:24 13:49:25 : ..\..\sources\PSOWLListenerProxyBase.cpp : 54 : REQUIRE failed

Does anyone know how to fix that error?

**Comment by corbindavenport** [comment]
I just re-installed it on Ubuntu 17.10 64-bit and it seems to work fine. What distro/architecture are you using?

**Comment by corbindavenport** [comment]
I assume you don't need help anymore, so I'll close this issue. If you're still having problems, feel free to re-open it and let me know.
